language: node_js

node_js:
   "16.20.2"

cache:
  directories:
    - node_modules
  yarn: true

install:
  - yarn install

script:
 - yarn lint
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  email: giri.chippada@gmail.com
  name: Giri Babu Chippada
  target-branch: master
  on:
    branch: development
